Dont upload dev release in cf-network performance-sd
Do not create and upload another development release of cf-networking
when deploying the deployment for the service discovery performance
tests.

Prevents:
```
Error: Release version 'cf-networking/3.33.0+dev.1696436635' not found in deployment 'cf' manifest
```
Src: https://ci.funtime.lol/teams/networking/pipelines/new-networking-release/jobs/export-release/builds/9#L651d952d:9

Before this change, in the case that `export-release` runs after
`run-service-discovery-performance-tests`, `export-release` will fail
because the deployment of the `performance-sd.yml` manifest for the
service discovery performance tests causes a new development release of
cf-networking to be created and uploaded.

Ultimately, we don't need a new dev release, because the new pipeline
design creates and uploads development releases in the `prepare-env`
job, before running any acceptance tests or exporting the releases.

Signed-off-by: Josh Russett <jrussett@vmware.com>